-- T_APPLICATION_DOWNTIME 

DROP TABLE IF EXISTS T_APPLICATION_DOWNTIME;

CREATE TABLE T_APPLICATION_DOWNTIME (
	APPLICATION_ID VARCHAR(25) NOT NULL,
	RECORDING_START DATETIME NOT NULL,
	RECORDING_END DATETIME,
	PRIMARY KEY  (APPLICATION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1
COMMENT='Stores the recording start & end times for applications';
	
-- T_APPLICATION_DOWNTIME_HISTORY	

DROP TABLE IF EXISTS T_APPLICATION_DOWNTIME_HISTORY;

CREATE TABLE T_APPLICATION_DOWNTIME_HISTORY(
	APPLICATION_ID VARCHAR(25) NOT NULL,
    START_TIME TIMESTAMP NOT NULL,
	END_TIME TIMESTAMP NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1
COMMENT='history of downtimes that apps experienced';
	
-- MBEAN_ATTRIBUTE

DROP TABLE IF EXISTS MBEAN_ATTRIBUTE;

CREATE TABLE MBEAN_ATTRIBUTE(
	ID INT(10) unsigned NOT NULL auto_increment,
	APPLICATION_ID VARCHAR(25) NOT NULL,
	APPLICATION_NAME VARCHAR(100) NOT NULL,
	MBEAN_NAME VARCHAR(512) NOT NULL,
	ATTRIBUTE_NAME VARCHAR(256) NOT NULL,
	PRIMARY KEY(ID)	
) ENGINE=InnoDB DEFAULT CHARSET=latin1
COMMENT='mbean attributes for which the values should be recorded';

insert into MBEAN_ATTRIBUTE(APPLICATION_ID, APPLICATION_NAME, MBEAN_NAME, ATTRIBUTE_NAME)
	 values(1, 'jManage', 'java.lang:type=Threading', 'ThreadCount');

insert into MBEAN_ATTRIBUTE(APPLICATION_ID, APPLICATION_NAME, MBEAN_NAME, ATTRIBUTE_NAME)
	 values(1, 'jManage', 'java.lang:type=Threading', 'DaemonThreadCount');

insert into MBEAN_ATTRIBUTE(APPLICATION_ID, APPLICATION_NAME, MBEAN_NAME, ATTRIBUTE_NAME)
	 values(1, 'jManage', 'java.lang:type=Threading', 'PeakThreadCount');

-- MBEAN_ATTRIBUTE_VALUE

DROP TABLE IF EXISTS MBEAN_ATTRIBUTE_VALUE;

CREATE TABLE MBEAN_ATTRIBUTE_VALUE(
	WHEN_COLLECTED DATETIME NOT NULL,
	MBEAN_ATTRIBUTE_ID INT(10) unsigned NOT NULL,
	VALUE VARCHAR(2000) NOT NULL,
	PRIMARY KEY(WHEN_COLLECTED, MBEAN_ATTRIBUTE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1
COMMENT='Stores that historical mbean attribute values';
